### ISSUE TITLE
关于bruter.py的bar.log.start()出错

### ISSUE THREAD

**Issue by labixx21** [H4ckForJob/dirmap#10]
Traceback (most recent call last):
  File "/root/dirmap/lib/controller/engine.py", line 44, in scan
    bruter(target)
  File "/root/dirmap/lib/controller/bruter.py", line 517, in bruter
    bar.log.start(tasks.task_length)
TypeError: start() takes 1 positional argument but 2 were given

**Comment by H4ckForJob** [comment]
首先，请git clone最新版本：）

关于bruter.py的bar.log.start()出错。解决方案：请安装progressbar2。卸载progressbar。防止导入同名模块。感谢某位表哥提醒。

```shell
执行命令：
python3 -m pip uninstall progressbar
python3 -m pip install progressbar2
```
