### ISSUE TITLE
在使用-iF urls.txt -lcf扫大量域名时会报错

### ISSUE THREAD

**Issue by thatqier** [H4ckForJob/dirmap#2]
File "/dirmap/lib/controller/bruter.py", line 459, in boss
    worker()
File "//dirmap/lib/controller/bruter.py", line 450, in worker
    bar.log.update(tasks.task_count)
File "/python/lib/python3.7/site-packages/progressbar/bar.py", line 565, in update
    % (value, self.min_value, self.max_value))
ValueError: Value 175699 is out of range, should be between 0 and 5715
2019-04-28T09:21:54Z <Greenlet at 0x10bac2ae8: boss> failed with ValueError

**Comment by 7x4uk4** [comment]
遇到同样的问题
Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 766, in gevent._greenlet.Greenlet.run
  File "/Users/xxxx/Python/dirmap/lib/controller/bruter.py", line 459, in boss
    worker()
  File "/Users/xxxx/Python/dirmap/lib/controller/bruter.py", line 450, in worker
    bar.log.update(tasks.task_count)
  File "/usr/local/lib/python3.7/site-packages/progressbar/bar.py", line 565, in update
    % (value, self.min_value, self.max_value))
ValueError: Value 338 is out of range, should be between 0 and 17
2019-04-29T01:15:39Z <Greenlet at 0x10c5ace18: boss> failed with ValueError

**Comment by B0luo** [comment]
遇到同样的问题，虽然报错，但是会生成结果

**Comment by H4ckForJob** [comment]
由于计算总数错误导致的问题，已修复
