### ISSUE TITLE
运行出错

### ISSUE THREAD

**Issue by bufsnake** [H4ckForJob/dirmap#46]
```bash
[*] Initialize targets...
[+] Load targets from: http://192.168.113.232/
[+] Set the number of thread: 30
[+] Coroutine mode
[+] Current target: http://192.168.113.232/
[*] Launching auto check 404
[+] Checking with: http://192.168.113.232/sqopyrqypkvnyynxpefbtiswjvcuupyacdbdfrukgl
[*] Use recursive scan: No
[*] Use dict mode
[+] Load dict:/Users/bufsnake/Web-Pentest/dirmap/data/dict_mode_dict.txt
[*] Use crawl mode
Traceback (most recent call last):
  File "/Users/bufsnake/Web-Pentest/dirmap/lib/controller/engine.py", line 44, in scan
    bruter(target)
  File "/Users/bufsnake/Web-Pentest/dirmap/lib/controller/bruter.py", line 586, in bruter
    bar.log.start(tasks.task_length)
TypeError: start() takes 1 positional argument but 2 were given
```

> 没有修改配置文件

**Comment by saoqi4826** [comment]
俺也是这样

**Comment by evilc0deooo** [comment]
我也遇到了这个问题，请问表哥解决了吗？

**Comment by bufsnake** [comment]
> 我也遇到了这个问题，请问表哥解决了吗？

> 更换python3版本

**Comment by evilc0deooo** [comment]
很早之前已经解决了，忘记来回答了，原因是因为 dirmap.conf 配置文件设置有问题，#扫描模式处理配置(4个模式，1次只能选择1个)，可以直接重新克隆dirmap项目到本地即可，如果想添加别的扫描字典直接在默认的字典加入就可以。

**Comment by H4ckForJob** [comment]
hello，之前遇到这个问题，大多是因为使用了不同版本的progressbar，解决方案，执行命令：
```
python3 -m pip uninstall progressbar
python3 -m pip install progressbar2
```

**Comment by labixx21** [comment]
遇到相同问题未能解决

**Comment by Mote-Z** [comment]
> hello，之前遇到这个问题，大多是因为使用了不同版本的progressbar，解决方案，执行命令：
> 
> ```
> python3 -m pip uninstall progressbar
> python3 -m pip install progressbar2
> ```

这个可以

**Comment by ghost** [comment]
> hello，之前遇到这个问题，大多是因为使用了不同版本的progressbar，解决方案，执行命令：
> 
> ```
> python3 -m pip uninstall progressbar
> python3 -m pip install progressbar2
> ```

太赞了，这个可以
