### ISSUE TITLE
按格式使用，报错 TypeError: start() takes 1 positional argument but 2 were given

### ISSUE THREAD

**Issue by sherlockzm** [H4ckForJob/dirmap#59]
按格式使用，报错：python3 dirmap.py -i http://XX.XX.XX.XX -lcf

Traceback (most recent call last):
  File "/home/kali/tools/scanDir/dirmap/lib/controller/engine.py", line 44, in scan                                                                        
    bruter(target)                                                                                                                                         
  File "/home/kali/tools/scanDir/dirmap/lib/controller/bruter.py", line 586, in bruter                                                                     
    bar.log.start(tasks.task_length)                                                                                                                       
TypeError: start() takes 1 positional argument but 2 were given

**Comment by banmabanm** [comment]
一样啊

**Comment by banmabanm** [comment]
你解决了吗

**Comment by leojjj** [comment]
+1

**Comment by ysgncss** [comment]
+1

**Comment by ysgncss** [comment]
原因找到了，请安装progressbar2。卸载progressbar。防止导入同名模块(汗)

执行命令：

python3 -m pip uninstall progressbar
python3 -m pip install progressbar2
