### ISSUE TITLE
fuzz mode TypeError: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by Ran-Xing** [H4ckForJob/dirmap#67]
```
 ✗ dirmap -i 10.1.8.172 -lcf       

                     #####  # #####  #    #   ##   #####
                     #    # # #    # ##  ##  #  #  #    #
                     #    # # #    # # ## # #    # #    #
                     #    # # #####  #    # ###### #####
                     #    # # #   #  #    # #    # #
                     #####  # #    # #    # #    # #   v1.0

[*] Initialize targets...
[+] Load targets from: 10.1.
[+] Set the number of thread: 30
[+] Coroutine mode
[+] Current target: http://10.1.                                   
[*] Launching auto check 404
[+] Checking with: http://10.1/rjdggechhjxrmebimyyyoylrfegkmilasxxoxfvjpo
[*] Use recursive scan: Yes                                                    
[*] Use fuzz mode
Traceback (most recent call last):
  File "/dirmap/lib/controller/engine.py", line 44, in scan
    bruter(target)
  File "/dirmap/lib/controller/bruter.py", line 573, in bruter
    for payload in payloads.all_payloads:
TypeError: 'NoneType' object is not iterable
```

**Comment by Mr-LiT** [comment]
This bug is due to the fuzz mode being turned on
But I don't know why this bug appers, I'm still looking for the reason

**Comment by H4ckForJob** [comment]
可能是插入的标签未转义照成的问题，例如fuzz的标签为`{dir}`，那么`{`和`}`需要转义。
另外一种解决方案是更改fuzz标签为其他字符串，详情见配置项`conf.fuzz_mode_label`

**Comment by hary654321** [comment]
还是有这个问题啊
