### ISSUE TITLE
TypeError: start() takes 1 positional argument but 2 were given

### ISSUE THREAD

**Issue by N0o01** [H4ckForJob/dirmap#71]
Traceback (most recent call last):
  File "/Users/zzzzDownloads/dirmap-master/lib/controller/engine.py", line 44, in scan
    bruter(target)
  File "/Users/zzzzz/Downloads/dirmap-master/lib/controller/bruter.py", line 586, in bruter
    bar.log.start(tasks.task_length)
TypeError: start() takes 1 positional argument but 2 were given

**Comment by H4ckForJob** [comment]
![image](https://user-images.githubusercontent.com/39022267/171359564-1ba7e5fe-1908-4f1b-adf1-c94e802184b7.png)
