### ISSUE TITLE
使用时候出现TypeError: ProgressBar.start() takes 1 positional argument but 2 were given

### ISSUE THREAD

**Issue by Rotund-jere** [H4ckForJob/dirmap#77]
作者大大你好，今日在使用时候出现如下报错，麻烦帮看一下怎么解决呢?谢谢~
[*] Use crawl mode
Traceback (most recent call last):
  File "/usr/dirmap/dirmap-master/lib/controller/engine.py", line 44, in scan                                                                                         
    bruter(target)                                                                                                                                                    
  File "/usr/dirmap/dirmap-master/lib/controller/bruter.py", line 586, in bruter                                                                                      
    bar.log.start(tasks.task_length)                                                                                                                                  
TypeError: ProgressBar.start() takes 1 positional argument but 2 were given

**Comment by sln-1550** [comment]
我也碰到了这个问题，改两个地方可以解决。主要是ProgressBar新版的start()不需要参数了，强制要求上限是100；而且每次update的时候也要修改下数值，不要超过100。

**Comment by sln-1550** [comment]
刚刚看到readme里写了：2. 关于bruter.py第517行`bar.log.start()`出错。解决方案：请安装progressbar2。卸载progressbar。防止导入同名模块。感谢某位表哥提醒。

**Comment by H4ckForJob** [comment]
已知问题，参考readme中的解决方案
