### ISSUE TITLE
运行爬虫模式使用HTTPS协议提示出错

### ISSUE THREAD

**Issue by tlhszc** [H4ckForJob/dirmap#9]
提示如下
[*] Use recursive scan: No                                                     
[*] Use crawl mode
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 343, in _make_request
    self._validate_conn(conn)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 841, in _validate_conn
    conn.connect()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 364, in connect
    _match_hostname(cert, self.assert_hostname or server_hostname)
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 374, in _match_hostname
    match_hostname(cert, asserted_hostname)
  File "/usr/lib/python3.7/ssl.py", line 327, in match_hostname
    % (hostname, dnsnames[0]))
ssl.SSLCertVerificationError: ("hostname '168hs.com' doesn't match 'job.168hs.com'",)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 398, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='168hs.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError("hostname '168hs.com' doesn't match 'job.168hs.com'")))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/dirmap/lib/controller/engine.py", line 44, in scan
    bruter(target)
  File "/root/dirmap/lib/controller/bruter.py", line 505, in bruter
    payloads.all_payloads = scanModeHandler()
  File "/root/dirmap/lib/controller/bruter.py", line 348, in scanModeHandler
    response = requests.get(conf.url, headers=headers, timeout=5)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 514, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='168hs.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError("hostname '168hs.com' doesn't match 'job.168hs.com'")))

root@kali:~/dirmap#

**Comment by H4ckForJob** [comment]
@tlhszc 你的目标网站使用的是http协议，非https协议，临时解决方法：将`-iU`参数输入换成`http://xxx.com`
